import fs from 'node:fs';

export const writeGeneratedScriptToFile = (
  generator: string,
  target: string,
  code: string,
) => {
  const fileContents = `/*
 * WARNING: This file was autogenerated using the script at:
 * ${generator}.
 * 
 * Do not edit manually.
 */
 ${code}
 `;

  fs.writeFileSync(target, fileContents, 'utf8');
};
