/*
 * WARNING: This file was autogenerated using the script at:
 * scripts/update-astro-shared-rules.ts.
 * 
 * Do not edit manually.
 */
 
import type { Linter } from 'eslint';

export const astroSharedRules: Record<string, Linter.RuleSeverity> = {
  "no-var": "error",
  "prefer-const": "error",
  "prefer-rest-params": "error",
  "prefer-spread": "error",
  "no-implied-eval": "error",
  "no-throw-literal": "error",
  "prefer-promise-reject-errors": "error",
  "require-await": "error",
  "dot-notation": "error",
  "constructor-super": "off",
  "getter-return": "off",
  "no-class-assign": "off",
  "no-const-assign": "off",
  "no-dupe-args": "off",
  "no-dupe-class-members": "off",
  "no-dupe-keys": "off",
  "no-func-assign": "off",
  "no-import-assign": "off",
  "no-new-native-nonconstructor": "off",
  "no-new-symbol": "off",
  "no-obj-calls": "off",
  "no-redeclare": "off",
  "no-setter-return": "off",
  "no-this-before-super": "off",
  "no-undef": "off",
  "no-unreachable": "off",
  "no-unsafe-negation": "off",
  "no-with": "off",
  "import-x/named": 0,
  "import-x/namespace": 0,
  "import-x/default": 0,
  "import-x/no-named-as-default-member": 0,
  "import-x/no-unresolved": 0
};

 