/*
 * WARNING: This file was autogenerated using the script at:
 * scripts/javascript-tseslint-rules.generated.ts.
 * 
 * Do not edit manually.
 */
 
import type { RuleConfig } from '@eslint/config-helpers';

export const javascriptTSEslintRules: Record<string, RuleConfig> = {
  "no-var": "error",
  "prefer-const": "error",
  "prefer-rest-params": "error",
  "prefer-spread": "error"
};

export const javascriptTSEslintTypedRulesInJs: Record<string, RuleConfig> = {
  "no-implied-eval": "error",
  "no-throw-literal": "error",
  "prefer-promise-reject-errors": "error",
  "require-await": "error",
  "dot-notation": "error"
};

 