/*
 * WARNING: This file is autogenerated using the
 * scripts/update-javascript-tseslint-rules.ts script.
 * 
 * Do not edit manually.
 */
import type { RuleConfig } from '@eslint/config-helpers';

export const javascriptTSEslintRules: Record<string, RuleConfig> = {
  "no-var": "error",
  "prefer-const": "error",
  "prefer-rest-params": "error",
  "prefer-spread": "error"
};

export const javascriptTSEslintTypedRulesInJs: Record<string, RuleConfig> = {
  "no-implied-eval": "error",
  "no-throw-literal": "error",
  "prefer-promise-reject-errors": "error",
  "require-await": "error",
  "dot-notation": "error"
};
