const generators = [
  './update-javascript-tseslint-rules.ts',
  // astro shared has to run after 'update-javascript-tseslint-rules.ts'
  // because it uses javascript config, which uses rules generated by it
  './update-astro-shared-rules.ts',
];

for (const generator of generators) {
  import(generator);
}
